# Generated by Django 5.0.4 on 2024-06-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='publication_date',
            field=models.CharField(max_length=50),
        ),
    ]
