# Generated by Django 5.0.4 on 2024-07-19 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_alter_searchresult_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('share', models.CharField(max_length=35)),
                ('checkedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=35)),
                ('content', models.TextField()),
                ('comment', models.CharField(max_length=25)),
                ('repost', models.CharField(max_length=30)),
                ('like', models.CharField(max_length=25)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.agenda')),
            ],
        ),
    ]
