# Generated by Django 3.2.25 on 2024-07-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_agenda_agendaresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgendaResult',
        ),
    ]
