# Generated by Django 3.2.25 on 2024-07-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_delete_agendaresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='share',
            field=models.CharField(max_length=100),
        ),
    ]
